name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: macos-15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test-ios18
      cancel-in-progress: true
    strategy:
      matrix:
        scheme: [MapLibreSwiftUI-Package]
        destination: [
            # TODO: Add more destinations (snapshot testing is the problem)
            "platform=iOS Simulator,name=iPhone 15,OS=17.5",
            # 'platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm)',
            # "platform=iOS Simulator,name=iPad (10th generation),OS=16.4",
            # "platform=iOS Simulator,name=iPhone 15,OS=17.2",
          ]
    name: Test ${{ matrix.destination }}

    steps:
      - name: Install tools
        run: brew update && brew upgrade xcbeautify

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: Checkout maplibre-swiftui-dsl-playground
        uses: actions/checkout@v4

      - name: Configure Package.swift for local development
        run: sed -i '' 's/let enableDeveloperTools = false/let enableDeveloperTools = true/' Package@swift-5.9.swift

      - name: Disable SPM Prebuilts
        run: defaults write com.apple.dt.Xcode IDEPackageEnablePrebuilts NO

      - name: Test ${{ matrix.scheme }} on ${{ matrix.destination }}
        run: xcodebuild -scheme ${{ matrix.scheme }} test -skipMacroValidation -destination '${{ matrix.destination }}' | xcbeautify && exit ${PIPESTATUS[0]}
